/**
 * ISO country per Cloudflare data-center IATA code, for the fleet page's
 * agent-location flags. Static on purpose: the trace endpoint's `loc` field
 * geolocates the WORKER'S EGRESS IP (Cloudflare's own ranges, whose geo
 * records move around - one re-mapping turned the whole fleet Canadian),
 * while the colo code is stable ground truth. Unknown colos resolve to null
 * and render without a flag; extend the map as new colos show up.
 */
const COLO_COUNTRIES: Record<string, string> = {
	// North America
	ATL: 'US',
	BOS: 'US',
	BUF: 'US',
	CLT: 'US',
	ORD: 'US',
	DFW: 'US',
	DEN: 'US',
	DTW: 'US',
	EWR: 'US',
	HNL: 'US',
	IAH: 'US',
	IAD: 'US',
	JAX: 'US',
	MCI: 'US',
	LAS: 'US',
	LAX: 'US',
	MIA: 'US',
	MSP: 'US',
	BNA: 'US',
	OMA: 'US',
	PHL: 'US',
	PHX: 'US',
	PDX: 'US',
	SLC: 'US',
	SAN: 'US',
	SFO: 'US',
	SJC: 'US',
	SEA: 'US',
	STL: 'US',
	TPA: 'US',
	PIT: 'US',
	RIC: 'US',
	SMF: 'US',
	ABQ: 'US',
	OKC: 'US',
	MEM: 'US',
	CMH: 'US',
	IND: 'US',
	MFE: 'US',
	FSD: 'US',
	YYZ: 'CA',
	YVR: 'CA',
	YUL: 'CA',
	YYC: 'CA',
	YWG: 'CA',
	YOW: 'CA',
	YHZ: 'CA',
	MEX: 'MX',
	QRO: 'MX',
	GDL: 'MX',
	// South America
	EZE: 'AR',
	GRU: 'BR',
	GIG: 'BR',
	CNF: 'BR',
	FOR: 'BR',
	POA: 'BR',
	CWB: 'BR',
	BOG: 'CO',
	SCL: 'CL',
	LIM: 'PE',
	UIO: 'EC',
	PTY: 'PA',
	SJO: 'CR',
	// Europe
	AMS: 'NL',
	ATH: 'GR',
	BCN: 'ES',
	MAD: 'ES',
	BEG: 'RS',
	TXL: 'DE',
	BRU: 'BE',
	OTP: 'RO',
	BUD: 'HU',
	CPH: 'DK',
	DUB: 'IE',
	DUS: 'DE',
	EDI: 'GB',
	FRA: 'DE',
	GVA: 'CH',
	ZRH: 'CH',
	HAM: 'DE',
	HEL: 'FI',
	IST: 'TR',
	ADB: 'TR',
	KBP: 'UA',
	LIS: 'PT',
	LHR: 'GB',
	MAN: 'GB',
	LUX: 'LU',
	MRS: 'FR',
	CDG: 'FR',
	LYS: 'FR',
	MXP: 'IT',
	FCO: 'IT',
	PMO: 'IT',
	MUC: 'DE',
	OSL: 'NO',
	PRG: 'CZ',
	RIX: 'LV',
	SOF: 'BG',
	ARN: 'SE',
	GOT: 'SE',
	TLL: 'EE',
	VIE: 'AT',
	VNO: 'LT',
	WAW: 'PL',
	ZAG: 'HR',
	SKP: 'MK',
	TIA: 'AL',
	KEF: 'IS',
	// Middle East & Africa
	AMM: 'JO',
	BAH: 'BH',
	DOH: 'QA',
	DXB: 'AE',
	KWI: 'KW',
	RUH: 'SA',
	JED: 'SA',
	TLV: 'IL',
	BGW: 'IQ',
	MCT: 'OM',
	CAI: 'EG',
	CMN: 'MA',
	CPT: 'ZA',
	JNB: 'ZA',
	DUR: 'ZA',
	LOS: 'NG',
	NBO: 'KE',
	DAR: 'TZ',
	ACC: 'GH',
	DKR: 'SN',
	MRU: 'MU',
	// Asia-Pacific
	BLR: 'IN',
	BOM: 'IN',
	DEL: 'IN',
	MAA: 'IN',
	HYD: 'IN',
	CCU: 'IN',
	COK: 'IN',
	BKK: 'TH',
	CGK: 'ID',
	DPS: 'ID',
	HAN: 'VN',
	SGN: 'VN',
	HKG: 'HK',
	ICN: 'KR',
	KUL: 'MY',
	MNL: 'PH',
	CEB: 'PH',
	NRT: 'JP',
	KIX: 'JP',
	FUK: 'JP',
	OKA: 'JP',
	SIN: 'SG',
	TPE: 'TW',
	KHH: 'TW',
	CGP: 'BD',
	DAC: 'BD',
	CMB: 'LK',
	KTM: 'NP',
	ISB: 'PK',
	KHI: 'PK',
	LHE: 'PK',
	PNH: 'KH',
	VTE: 'LA',
	RGN: 'MM',
	ULN: 'MN',
	AKL: 'NZ',
	CHC: 'NZ',
	ADL: 'AU',
	BNE: 'AU',
	CBR: 'AU',
	HBA: 'AU',
	MEL: 'AU',
	PER: 'AU',
	SYD: 'AU',
	GUM: 'GU',
	NOU: 'NC',
	SUV: 'FJ',
};

/** The colo's country, or null for a colo the map does not know yet. */
export function coloCountry(colo: string | null): string | null {
	if (!colo) return null;
	return COLO_COUNTRIES[colo.toUpperCase()] ?? null;
}
