// Generated by scripts/generate-migrations.mjs - do not edit.
//
// The SQL is inlined rather than imported from .sql files so this agent can be
// consumed as a plain npm dependency, with no Wrangler Text-module rule needed
// in the consumer's config. Regenerate with `npm run migrations`.

const journal = {
	"version": "7",
	"dialect": "sqlite",
	"entries": [
		{
			"idx": 0,
			"version": "6",
			"when": 1784483488397,
			"tag": "0000_worried_grim_reaper",
			"breakpoints": true
		},
		{
			"idx": 1,
			"version": "6",
			"when": 1784486196314,
			"tag": "0001_real_bastion",
			"breakpoints": true
		},
		{
			"idx": 2,
			"version": "6",
			"when": 1784489733764,
			"tag": "0002_stiff_daredevil",
			"breakpoints": true
		},
		{
			"idx": 3,
			"version": "6",
			"when": 1784512063872,
			"tag": "0003_reflective_tinkerer",
			"breakpoints": true
		},
		{
			"idx": 4,
			"version": "6",
			"when": 1784607935612,
			"tag": "0004_thin_hercules",
			"breakpoints": true
		},
		{
			"idx": 5,
			"version": "6",
			"when": 1786501645504,
			"tag": "0005_busy_cobalt_man",
			"breakpoints": true
		}
	]
};

const m0000 = `CREATE TABLE \`account\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`account_id\` text NOT NULL,
	\`provider_id\` text NOT NULL,
	\`user_id\` text NOT NULL,
	\`access_token\` text,
	\`refresh_token\` text,
	\`id_token\` text,
	\`access_token_expires_at\` integer,
	\`refresh_token_expires_at\` integer,
	\`scope\` text,
	\`password\` text,
	\`created_at\` integer NOT NULL,
	\`updated_at\` integer NOT NULL,
	FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE \`session\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`expires_at\` integer NOT NULL,
	\`token\` text NOT NULL,
	\`created_at\` integer NOT NULL,
	\`updated_at\` integer NOT NULL,
	\`ip_address\` text,
	\`user_agent\` text,
	\`user_id\` text NOT NULL,
	FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE UNIQUE INDEX \`session_token_unique\` ON \`session\` (\`token\`);--> statement-breakpoint
CREATE TABLE \`user\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`name\` text NOT NULL,
	\`email\` text NOT NULL,
	\`email_verified\` integer DEFAULT false NOT NULL,
	\`image\` text,
	\`created_at\` integer NOT NULL,
	\`updated_at\` integer NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX \`user_email_unique\` ON \`user\` (\`email\`);--> statement-breakpoint
CREATE TABLE \`verification\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`identifier\` text NOT NULL,
	\`value\` text NOT NULL,
	\`expires_at\` integer NOT NULL,
	\`created_at\` integer NOT NULL,
	\`updated_at\` integer NOT NULL
);
`;

const m0001 = `CREATE TABLE \`user_activity\` (
	\`day\` text NOT NULL,
	\`user_id\` text NOT NULL,
	PRIMARY KEY(\`day\`, \`user_id\`)
);
--> statement-breakpoint
ALTER TABLE \`session\` ADD \`country\` text;--> statement-breakpoint
ALTER TABLE \`user\` ADD \`is_anonymous\` integer;`;

const m0002 = `DROP TABLE \`user_activity\`;`;

const m0003 = `CREATE TABLE \`chat_message\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`client_key\` text NOT NULL,
	\`role\` text NOT NULL,
	\`content\` text NOT NULL,
	\`created_at\` integer NOT NULL
);
--> statement-breakpoint
CREATE INDEX \`chat_message_client_created_idx\` ON \`chat_message\` (\`client_key\`,\`created_at\`);`;

const m0004 = `CREATE TABLE \`jwks\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`public_key\` text NOT NULL,
	\`private_key\` text NOT NULL,
	\`created_at\` integer NOT NULL,
	\`expires_at\` integer
);
--> statement-breakpoint
ALTER TABLE \`user\` ADD \`role\` text DEFAULT 'user' NOT NULL;`;

const m0005 = `CREATE TABLE \`invitation\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`organization_id\` text NOT NULL,
	\`email\` text NOT NULL,
	\`role\` text,
	\`status\` text DEFAULT 'pending' NOT NULL,
	\`expires_at\` integer NOT NULL,
	\`created_at\` integer NOT NULL,
	\`inviter_id\` text NOT NULL,
	FOREIGN KEY (\`organization_id\`) REFERENCES \`organization\`(\`id\`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (\`inviter_id\`) REFERENCES \`user\`(\`id\`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE INDEX \`invitation_organization_idx\` ON \`invitation\` (\`organization_id\`);--> statement-breakpoint
CREATE INDEX \`invitation_email_idx\` ON \`invitation\` (\`email\`);--> statement-breakpoint
CREATE TABLE \`member\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`organization_id\` text NOT NULL,
	\`user_id\` text NOT NULL,
	\`role\` text DEFAULT 'member' NOT NULL,
	\`created_at\` integer NOT NULL,
	FOREIGN KEY (\`organization_id\`) REFERENCES \`organization\`(\`id\`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE INDEX \`member_organization_idx\` ON \`member\` (\`organization_id\`);--> statement-breakpoint
CREATE INDEX \`member_user_idx\` ON \`member\` (\`user_id\`);--> statement-breakpoint
CREATE TABLE \`organization\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`name\` text NOT NULL,
	\`slug\` text NOT NULL,
	\`logo\` text,
	\`metadata\` text,
	\`created_at\` integer NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX \`organization_slug_unique\` ON \`organization\` (\`slug\`);--> statement-breakpoint
ALTER TABLE \`session\` ADD \`active_organization_id\` text;`;

export default {
	journal,
	migrations: {
		m0000,
		m0001,
		m0002,
		m0003,
		m0004,
		m0005
	}
};
