<script lang="ts">
	import * as Table from '$lib/components/ui/table';
	import { Badge } from '$lib/components/ui/badge';
	import { Button } from '$lib/components/ui/button';
	import { Input } from '$lib/components/ui/input';
	import { SvelteMap } from 'svelte/reactivity';

	let { data } = $props();

	const base = $derived(data.base ?? 'https://geo-astro-site.foodstarmelbourne.workers.dev');

	type Entry = { loc: string; path: string; lastmod: string | null };

	function sectionOf(path: string): string {
		return path === '/' ? '(root)' : path.split('/')[1];
	}

	// ── Filters + sorting ──
	let search = $state('');
	let section = $state<string | null>(null);
	type SortKey = 'path' | 'lastmod' | 'status';
	let sortKey = $state<SortKey | ''>('');
	let sortDir = $state<'asc' | 'desc'>('asc');

	function toggleSort(key: SortKey) {
		if (sortKey === key) {
			sortDir = sortDir === 'asc' ? 'desc' : 'asc';
		} else {
			sortKey = key;
			sortDir = key === 'status' ? 'desc' : 'asc';
		}
		page = 1;
	}

	function caret(key: SortKey): string {
		if (sortKey !== key) return '';
		return sortDir === 'asc' ? ' ▲' : ' ▼';
	}

	const filtered = $derived.by(() => {
		let list: Entry[] = data.entries ?? [];
		if (section) list = list.filter((e) => sectionOf(e.path) === section);
		const q = search.trim().toLowerCase();
		if (q) list = list.filter((e) => e.path.toLowerCase().includes(q));
		if (sortKey) {
			const dir = sortDir === 'asc' ? 1 : -1;
			const key = sortKey === 'lastmod' ? ('lastmod' as const) : ('path' as const);
			list = [...list].sort((a, b) => {
				if (sortKey === 'status') {
					return ((statuses.get(a.loc) ?? -1) - (statuses.get(b.loc) ?? -1)) * dir;
				}
				return String(a[key] ?? '').localeCompare(String(b[key] ?? '')) * dir;
			});
		}
		return list;
	});

	// ── Pagination (50 / page) ──
	const PER_PAGE = 50;
	let page = $state(1);
	const totalPages = $derived(Math.max(1, Math.ceil(filtered.length / PER_PAGE)));
	const pageEntries = $derived(filtered.slice((page - 1) * PER_PAGE, page * PER_PAGE));

	// ── Status checking (batched through check.json) ──
	const BATCH = 25;
	const statuses = new SvelteMap<string, number>();
	let checking = $state(false);
	let progress = $state(0);
	let cancelRequested = $state(false);

	const failedCount = $derived([...statuses.values()].filter((s) => s === 0 || s >= 400).length);

	async function checkAll() {
		if (checking || data.missing) return;
		checking = true;
		cancelRequested = false;
		statuses.clear();
		progress = 0;
		const all: Entry[] = data.entries ?? [];
		for (let i = 0; i < all.length; i += BATCH) {
			if (cancelRequested) break;
			const slice = all.slice(i, i + BATCH);
			try {
				const res = await fetch('/dashboard/geo-site/content/sitemap/check.json', {
					method: 'POST',
					headers: { 'content-type': 'application/json' },
					body: JSON.stringify({ urls: slice.map((e) => e.loc) })
				});
				if (res.ok) {
					const body = (await res.json()) as { statuses?: { loc: string; status: number }[] };
					for (const s of body.statuses ?? []) statuses.set(s.loc, s.status);
				}
			} catch {
				// Network hiccup on one batch: leave those unchecked, keep going.
			}
			progress = Math.min(i + BATCH, all.length);
		}
		checking = false;
	}

	// ── Copy all URLs ──
	let copied = $state(false);
	async function copyAll() {
		try {
			await navigator.clipboard.writeText((data.entries ?? []).map((e: Entry) => e.loc).join('\n'));
			copied = true;
			setTimeout(() => (copied = false), 2000);
		} catch {
			// Clipboard blocked (insecure context) — no-op.
		}
	}
</script>

<svelte:head>
	<title>Sitemap · Geo Admin · Cloudflarebase</title>
	<meta name="robots" content="noindex" />
</svelte:head>

<div class="mx-auto max-w-full space-y-6 px-3 py-5 sm:px-6 sm:py-8">
	{#if data.missing}
		<div class="rounded-lg border border-dashed p-6">
			<h1 class="text-2xl font-bold tracking-tight">Sitemap</h1>
			<p class="mt-3 text-sm text-muted-foreground">
				<code class="rounded bg-muted px-1.5 py-0.5 font-mono text-xs">/sitemap.xml</code>
				does not exist on geo-astro-site yet. It is generated by
				<code class="rounded bg-muted px-1.5 py-0.5 font-mono text-xs"
					>scripts/generate-sitemap.mjs</code
				>
				during the site's CI build — merge the site's <span class="font-mono">preview</span> branch
				to
				<span class="font-mono">master</span> and reload this page.
			</p>
		</div>
	{:else}
		<div class="flex flex-wrap items-center justify-between gap-3">
			<div>
				<h1 class="text-2xl font-bold tracking-tight">Sitemap</h1>
				<p class="text-sm text-muted-foreground">
					{data.count} URLs ·
					<a
						href="{base}/sitemap.xml"
						target="_blank"
						rel="noopener"
						class="text-blue-500 hover:underline">sitemap.xml</a
					>
					{#if data.fetchedAt}
						· fetched {new Date(data.fetchedAt).toLocaleTimeString()}
					{/if}
				</p>
			</div>
			<div class="flex flex-wrap items-center gap-2">
				<Button
					size="sm"
					variant="outline"
					type="button"
					onclick={copyAll}
					data-testid="sitemap-copy"
				>
					{copied ? 'Copied ✓' : 'Copy all URLs'}
				</Button>
				<Button
					size="sm"
					variant="outline"
					type="button"
					onclick={checkAll}
					disabled={checking}
					data-testid="sitemap-check"
				>
					{checking ? `Checking… ${progress}/${data.count}` : 'Check statuses'}
				</Button>
				{#if checking}
					<Button size="sm" variant="ghost" type="button" onclick={() => (cancelRequested = true)}>
						Cancel
					</Button>
				{/if}
			</div>
		</div>

		{#if checking || statuses.size > 0}
			<div class="flex items-center gap-3 text-sm">
				<Badge variant="secondary" class="text-xs">{statuses.size} checked</Badge>
				{#if failedCount > 0}
					<Badge variant="destructive" class="text-xs">{failedCount} failing</Badge>
				{:else if statuses.size > 0}
					<Badge variant="outline" class="border-green-600/40 text-xs text-green-600">all OK</Badge>
				{/if}
				{#if checking}
					<span class="h-2 w-2 animate-pulse rounded-full bg-primary"></span>
				{/if}
			</div>
		{/if}

		<!-- Section chips: click to filter, click again to clear -->
		<div class="flex flex-wrap gap-2">
			{#each data.sections as s (s.name)}
				<button
					type="button"
					class={[
						'rounded-full border px-3 py-1 text-xs font-medium transition-colors',
						section === s.name
							? 'border-primary bg-primary/10 text-primary'
							: 'text-muted-foreground hover:bg-accent hover:text-accent-foreground'
					]}
					onclick={() => {
						section = section === s.name ? null : s.name;
						page = 1;
					}}
				>
					/{s.name === '(root)' ? '' : s.name} · {s.count}
				</button>
			{/each}
		</div>

		<div class="flex items-center gap-2">
			<Input
				bind:value={search}
				placeholder="Filter by path…"
				class="max-w-sm"
				oninput={() => (page = 1)}
			/>
			{#if totalPages > 1}
				<span class="text-xs text-muted-foreground"
					>{filtered.length} shown · page {page} / {totalPages}</span
				>
			{/if}
		</div>

		<div class="rounded-lg border">
			<Table.Root class="w-full table-fixed">
				<Table.Header>
					<Table.Row>
						<Table.Head class="w-[48px]">#</Table.Head>
						<Table.Head class="cursor-pointer select-none" onclick={() => toggleSort('path')}
							>URL{caret('path')}</Table.Head
						>
						<Table.Head class="w-[140px]">Section</Table.Head>
						<Table.Head
							class="w-[130px] cursor-pointer select-none"
							onclick={() => toggleSort('lastmod')}>Last modified{caret('lastmod')}</Table.Head
						>
						<Table.Head
							class="w-[90px] cursor-pointer select-none"
							onclick={() => toggleSort('status')}>Status{caret('status')}</Table.Head
						>
					</Table.Row>
				</Table.Header>
				<Table.Body>
					{#each pageEntries as e, idx ((page - 1) * PER_PAGE + idx)}
						<Table.Row>
							<Table.Cell class="text-xs text-muted-foreground tabular-nums"
								>{(page - 1) * PER_PAGE + idx + 1}</Table.Cell
							>
							<Table.Cell class="font-mono text-xs">
								<!-- eslint-disable svelte/no-navigation-without-resolve -- external absolute URL on geo-astro-site, not a local route -->
								<a
									href={e.loc}
									target="_blank"
									rel="noopener"
									class="truncate text-blue-500 hover:underline">{e.path}</a
								>
								<!-- eslint-enable svelte/no-navigation-without-resolve -->
							</Table.Cell>
							<Table.Cell class="text-xs text-muted-foreground">{sectionOf(e.path)}</Table.Cell>
							<Table.Cell class="text-xs text-muted-foreground tabular-nums">
								{e.lastmod ?? '—'}
							</Table.Cell>
							<Table.Cell>
								{#if statuses.has(e.loc)}
									{@const s = statuses.get(e.loc)!}
									<Badge
										variant={s === 0 || s >= 400 ? 'destructive' : 'outline'}
										class={[
											'text-xs',
											s >= 200 && s < 300
												? 'border-green-600/40 text-green-600'
												: s >= 300 && s < 400
													? 'border-blue-500/40 text-blue-500'
													: ''
										]}
										data-testid="status-{s}"
									>
										{s === 0 ? 'ERR' : s}
									</Badge>
								{:else}
									<span class="text-xs text-muted-foreground">—</span>
								{/if}
							</Table.Cell>
						</Table.Row>
					{/each}
				</Table.Body>
			</Table.Root>
		</div>

		{#if totalPages > 1}
			<div class="flex items-center justify-center gap-2">
				<Button
					size="sm"
					variant="outline"
					type="button"
					onclick={() => (page = Math.max(1, page - 1))}
					disabled={page <= 1}>Prev</Button
				>
				<span class="text-sm text-muted-foreground">Page {page} of {totalPages}</span>
				<Button
					size="sm"
					variant="outline"
					type="button"
					onclick={() => (page = Math.min(totalPages, page + 1))}
					disabled={page >= totalPages}>Next</Button
				>
			</div>
		{/if}
	{/if}
</div>
