// Minimal parser for the geo-astro-site sitemap.xml (created by
// scripts/generate-sitemap.mjs). Regex-based on purpose: the XML is
// machine-generated by a known writer, so a dependency-free parse is exact.

export interface SitemapEntry {
	/** Absolute URL as written in <loc>. */
	loc: string;
	/** URL-decoded pathname (+search) for binding fetches. */
	path: string;
	/** <lastmod> date (YYYY-MM-DD) or null. */
	lastmod: string | null;
}

export function parseSitemapXml(xml: string): SitemapEntry[] {
	const entries: SitemapEntry[] = [];
	const urlBlocks = xml.matchAll(/<url>([\s\S]*?)<\/url>/g);
	for (const block of urlBlocks) {
		const loc = block[1].match(/<loc>([^<]+)<\/loc>/)?.[1]?.trim();
		if (!loc) continue;
		const lastmod = block[1].match(/<lastmod>([^<]+)<\/lastmod>/)?.[1]?.trim() ?? null;
		// Sitemap XML entities are pre-escaped by the writer; undo the ones
		// that can legally appear in a URL.
		const unescaped = loc
			.replaceAll('&amp;', '&')
			.replaceAll('&lt;', '<')
			.replaceAll('&gt;', '>')
			.replaceAll('&quot;', '"')
			.replaceAll('&apos;', "'");
		let path: string;
		try {
			const u = new URL(unescaped);
			path = u.pathname + u.search;
		} catch {
			continue;
		}
		entries.push({ loc: unescaped, path, lastmod: lastmod || null });
	}
	return entries.sort((a, b) => a.path.localeCompare(b.path));
}
