// Generated by scripts/generate-migrations.mjs - do not edit.
//
// The SQL is inlined rather than imported from .sql files so this agent can be
// consumed as a plain npm dependency, with no Wrangler Text-module rule needed
// in the consumer's config. Regenerate with `npm run migrations`.

const journal = {
	version: '7',
	dialect: 'sqlite',
	entries: [
		{
			idx: 0,
			version: '6',
			when: 1786845812561,
			tag: '0000_keen_vulture',
			breakpoints: true,
		},
		{
			idx: 1,
			version: '6',
			when: 1786983472279,
			tag: '0001_handy_the_captain',
			breakpoints: true,
		},
	],
};

const m0000 = `CREATE TABLE \`buckets\` (
	\`name\` text PRIMARY KEY NOT NULL,
	\`read_access\` text DEFAULT 'auth' NOT NULL,
	\`write_access\` text DEFAULT 'auth' NOT NULL,
	\`read_permission\` text,
	\`write_permission\` text,
	\`public_listing\` integer DEFAULT false NOT NULL,
	\`max_object_bytes\` integer,
	\`allowed_content_types\` text,
	\`cache_control\` text,
	\`config_version\` integer DEFAULT 1 NOT NULL,
	\`object_count\` integer DEFAULT 0 NOT NULL,
	\`total_bytes\` integer DEFAULT 0 NOT NULL,
	\`created_at\` integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE \`objects\` (
	\`key\` text PRIMARY KEY NOT NULL,
	\`size\` integer NOT NULL,
	\`etag\` text NOT NULL,
	\`content_type\` text DEFAULT 'application/octet-stream' NOT NULL,
	\`owner\` text DEFAULT '' NOT NULL,
	\`created_at\` integer NOT NULL,
	\`updated_at\` integer NOT NULL
);
--> statement-breakpoint
CREATE INDEX \`objects_owner_key_idx\` ON \`objects\` (\`owner\`,\`key\`);`;

const m0001 = `CREATE TABLE \`uploads\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`bucket\` text NOT NULL,
	\`key\` text NOT NULL,
	\`r2_upload_id\` text NOT NULL,
	\`part_size\` integer NOT NULL,
	\`reserved_bytes\` integer NOT NULL,
	\`content_type\` text DEFAULT 'application/octet-stream' NOT NULL,
	\`owner\` text DEFAULT '' NOT NULL,
	\`created_at\` integer NOT NULL
);
--> statement-breakpoint
CREATE INDEX \`uploads_created_idx\` ON \`uploads\` (\`created_at\`);--> statement-breakpoint
CREATE INDEX \`uploads_bucket_idx\` ON \`uploads\` (\`bucket\`);`;

export default {
	journal,
	migrations: {
		m0000,
		m0001,
	},
};
