// Generated by scripts/generate-migrations.mjs - do not edit.
//
// The SQL is inlined rather than imported from .sql files so this agent can be
// consumed as a plain npm dependency, with no Wrangler Text-module rule needed
// in the consumer's config. Regenerate with `npm run migrations`.

const journal = {
	"version": "7",
	"dialect": "sqlite",
	"entries": [
		{
			"idx": 0,
			"version": "6",
			"when": 1786556374566,
			"tag": "0000_red_la_nuit",
			"breakpoints": true
		}
	]
};

const m0000 = `CREATE TABLE \`apps\` (
	\`name\` text PRIMARY KEY NOT NULL,
	\`subdomain\` text NOT NULL,
	\`created_at\` integer NOT NULL,
	\`last_deploy_at\` integer,
	\`deploy_count\` integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE \`deploys\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`app_name\` text NOT NULL,
	\`subdomain\` text NOT NULL,
	\`status\` text NOT NULL,
	\`has_worker\` integer NOT NULL,
	\`asset_count\` integer NOT NULL,
	\`asset_bytes\` integer NOT NULL,
	\`module_bytes\` integer NOT NULL,
	\`created_at\` integer NOT NULL
);
`;

export default {
	journal,
	migrations: {
		m0000
	}
};
