// Generated by scripts/generate-migrations.mjs - do not edit.
//
// The SQL is inlined rather than imported from .sql files so this agent can be
// consumed as a plain npm dependency, with no Wrangler Text-module rule needed
// in the consumer's config. Regenerate with `npm run migrations`.

const journal = {
	version: '7',
	dialect: 'sqlite',
	entries: [
		{
			idx: 0,
			version: '6',
			when: 1785365009827,
			tag: '0000_swift_lethal_legion',
			breakpoints: true,
		},
		{
			idx: 1,
			version: '6',
			when: 1785425136947,
			tag: '0001_moaning_beast',
			breakpoints: true,
		},
		{
			idx: 2,
			version: '6',
			when: 1785428742608,
			tag: '0002_gigantic_sleeper',
			breakpoints: true,
		},
	],
};

const m0000 = `CREATE TABLE \`collection_meta\` (
	\`id\` integer PRIMARY KEY NOT NULL,
	\`config\` text NOT NULL,
	\`updated_at\` integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE \`collections\` (
	\`name\` text PRIMARY KEY NOT NULL,
	\`read_access\` text DEFAULT 'auth' NOT NULL,
	\`write_access\` text DEFAULT 'auth' NOT NULL,
	\`docs\` integer DEFAULT 0 NOT NULL,
	\`created_at\` integer NOT NULL,
	\`reported_at\` integer
);
--> statement-breakpoint
CREATE TABLE \`documents\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`data\` text NOT NULL,
	\`owner\` text,
	\`created_at\` integer NOT NULL,
	\`updated_at\` integer NOT NULL
);
--> statement-breakpoint
CREATE INDEX \`documents_updated_at\` ON \`documents\` (\`updated_at\`);--> statement-breakpoint
CREATE INDEX \`documents_owner\` ON \`documents\` (\`owner\`);--> statement-breakpoint
CREATE TABLE \`subscriptions\` (
	\`conn_id\` text NOT NULL,
	\`sub_id\` text NOT NULL,
	\`query\` text NOT NULL,
	\`owner_sub\` text,
	\`token_exp\` integer,
	\`last_membership\` text,
	\`created_at\` integer NOT NULL,
	PRIMARY KEY(\`conn_id\`, \`sub_id\`)
);
--> statement-breakpoint
CREATE INDEX \`subscriptions_conn\` ON \`subscriptions\` (\`conn_id\`);`;

const m0001 = `ALTER TABLE \`collections\` ADD \`read_permission\` text;--> statement-breakpoint
ALTER TABLE \`collections\` ADD \`write_permission\` text;--> statement-breakpoint
ALTER TABLE \`collections\` ADD \`validator\` text;`;

const m0002 = `CREATE TABLE \`restore_points\` (
	\`id\` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	\`collection\` text NOT NULL,
	\`bookmark\` text NOT NULL,
	\`reason\` text NOT NULL,
	\`captured_at\` integer NOT NULL
);
--> statement-breakpoint
CREATE INDEX \`restore_points_collection\` ON \`restore_points\` (\`collection\`);`;

export default {
	journal,
	migrations: {
		m0000,
		m0001,
		m0002,
	},
};
