// Generated by scripts/generate-migrations.mjs - do not edit.
//
// The SQL is inlined rather than imported from .sql files so this agent can be
// consumed as a plain npm dependency, with no Wrangler Text-module rule needed
// in the consumer's config. Regenerate with `npm run migrations`.

const journal = {
	version: '7',
	dialect: 'sqlite',
	entries: [
		{
			idx: 0,
			version: '6',
			when: 1785365009827,
			tag: '0000_swift_lethal_legion',
			breakpoints: true,
		},
		{
			idx: 1,
			version: '6',
			when: 1785425136947,
			tag: '0001_moaning_beast',
			breakpoints: true,
		},
		{
			idx: 2,
			version: '6',
			when: 1785428742608,
			tag: '0002_gigantic_sleeper',
			breakpoints: true,
		},
		{
			idx: 3,
			version: '6',
			when: 1785899012221,
			tag: '0003_large_anthem',
			breakpoints: true,
		},
		{
			idx: 4,
			version: '6',
			when: 1785906574078,
			tag: '0004_luxuriant_marauders',
			breakpoints: true,
		},
		{
			idx: 5,
			version: '6',
			when: 1785908063017,
			tag: '0005_late_white_tiger',
			breakpoints: true,
		},
		{
			idx: 6,
			version: '6',
			when: 1785935152596,
			tag: '0006_black_infant_terrible',
			breakpoints: true,
		},
		{
			idx: 7,
			version: '6',
			when: 1785937604808,
			tag: '0007_sweet_morlocks',
			breakpoints: true,
		},
	],
};

const m0000 = `CREATE TABLE \`collection_meta\` (
	\`id\` integer PRIMARY KEY NOT NULL,
	\`config\` text NOT NULL,
	\`updated_at\` integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE \`collections\` (
	\`name\` text PRIMARY KEY NOT NULL,
	\`read_access\` text DEFAULT 'auth' NOT NULL,
	\`write_access\` text DEFAULT 'auth' NOT NULL,
	\`docs\` integer DEFAULT 0 NOT NULL,
	\`created_at\` integer NOT NULL,
	\`reported_at\` integer
);
--> statement-breakpoint
CREATE TABLE \`documents\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`data\` text NOT NULL,
	\`owner\` text,
	\`created_at\` integer NOT NULL,
	\`updated_at\` integer NOT NULL
);
--> statement-breakpoint
CREATE INDEX \`documents_updated_at\` ON \`documents\` (\`updated_at\`);--> statement-breakpoint
CREATE INDEX \`documents_owner\` ON \`documents\` (\`owner\`);--> statement-breakpoint
CREATE TABLE \`subscriptions\` (
	\`conn_id\` text NOT NULL,
	\`sub_id\` text NOT NULL,
	\`query\` text NOT NULL,
	\`owner_sub\` text,
	\`token_exp\` integer,
	\`last_membership\` text,
	\`created_at\` integer NOT NULL,
	PRIMARY KEY(\`conn_id\`, \`sub_id\`)
);
--> statement-breakpoint
CREATE INDEX \`subscriptions_conn\` ON \`subscriptions\` (\`conn_id\`);`;

const m0001 = `ALTER TABLE \`collections\` ADD \`read_permission\` text;--> statement-breakpoint
ALTER TABLE \`collections\` ADD \`write_permission\` text;--> statement-breakpoint
ALTER TABLE \`collections\` ADD \`validator\` text;`;

const m0002 = `CREATE TABLE \`restore_points\` (
	\`id\` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	\`collection\` text NOT NULL,
	\`bookmark\` text NOT NULL,
	\`reason\` text NOT NULL,
	\`captured_at\` integer NOT NULL
);
--> statement-breakpoint
CREATE INDEX \`restore_points_collection\` ON \`restore_points\` (\`collection\`);`;

const m0003 = `ALTER TABLE \`collections\` ADD \`kind\` text DEFAULT 'collection' NOT NULL;--> statement-breakpoint
ALTER TABLE \`collections\` ADD \`columns\` text;`;

const m0004 = `CREATE TABLE \`changelog\` (
	\`lsn\` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	\`op\` text NOT NULL,
	\`id\` text NOT NULL,
	\`image\` text,
	\`ts\` integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE \`replica_meta\` (
	\`id\` integer PRIMARY KEY NOT NULL,
	\`epoch\` integer DEFAULT 0 NOT NULL,
	\`applied_lsn\` integer DEFAULT 0 NOT NULL,
	\`pulled_at\` integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE \`replicas\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`region\` text NOT NULL,
	\`applied_lsn\` integer DEFAULT 0 NOT NULL,
	\`last_seen_at\` integer NOT NULL
);
--> statement-breakpoint
ALTER TABLE \`collections\` ADD \`replication\` text DEFAULT 'off' NOT NULL;--> statement-breakpoint
ALTER TABLE \`collections\` ADD \`rep_epoch\` integer DEFAULT 0 NOT NULL;`;

const m0005 = `ALTER TABLE \`replicas\` ADD \`push\` integer DEFAULT 0 NOT NULL;`;

const m0006 = `PRAGMA foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE \`__new_collections\` (
	\`name\` text PRIMARY KEY NOT NULL,
	\`kind\` text DEFAULT 'collection' NOT NULL,
	\`read_access\` text DEFAULT 'auth' NOT NULL,
	\`write_access\` text DEFAULT 'auth' NOT NULL,
	\`read_permission\` text,
	\`write_permission\` text,
	\`validator\` text,
	\`columns\` text,
	\`replication\` text DEFAULT 'auto' NOT NULL,
	\`rep_epoch\` integer DEFAULT 0 NOT NULL,
	\`docs\` integer DEFAULT 0 NOT NULL,
	\`created_at\` integer NOT NULL,
	\`reported_at\` integer
);
--> statement-breakpoint
INSERT INTO \`__new_collections\`("name", "kind", "read_access", "write_access", "read_permission", "write_permission", "validator", "columns", "replication", "rep_epoch", "docs", "created_at", "reported_at") SELECT "name", "kind", "read_access", "write_access", "read_permission", "write_permission", "validator", "columns", "replication", "rep_epoch", "docs", "created_at", "reported_at" FROM \`collections\`;--> statement-breakpoint
DROP TABLE \`collections\`;--> statement-breakpoint
ALTER TABLE \`__new_collections\` RENAME TO \`collections\`;--> statement-breakpoint
PRAGMA foreign_keys=ON;`;

const m0007 = `ALTER TABLE \`replicas\` ADD \`sockets\` integer DEFAULT 0 NOT NULL;`;

export default {
	journal,
	migrations: {
		m0000,
		m0001,
		m0002,
		m0003,
		m0004,
		m0005,
		m0006,
		m0007,
	},
};
